### ISSUE TITLE
软件下载服务器软件整理与管理

### ISSUE THREAD

**Issue by MiniBullLab** [MiniBullLab/easy_docker#11]
1.定义软件存放路径
2.测试软件下载服务器
3.对各个存放目录设置权限
4.与docker联调

**Comment by lpj0822** [comment]
目前在easy下建立目录
![image](https://user-images.githubusercontent.com/8148136/94530608-e6b14480-026d-11eb-8e34-9aee3354da3c.png)

**Comment by lpj0822** [comment]
目录pretrain_model是否可以设置下载权限

**Comment by vitahlin** [comment]
这个不适合放在这里了，需要的话只能单独再开一个端口。

**Comment by MiniBullLab** [comment]
@vitahlin 把还需要上传的软件在这里列举

**Comment by MiniBullLab** [comment]
easyai已经上传:/root/easy/software/easyai
@vitahlin
