### ISSUE TITLE
18.04上启动docker训练时没有使用GPU进行训练

### ISSUE THREAD

**Issue by foww-0001** [MiniBullLab/easy_docker#17]
在新的ubuntu18.04环境中，load镜像后，可以进行训练，但是训练很慢。查看nvidia显存使用，发现训练没有显存使用。
@lpj0822 @vitahlin

**Comment by lpj0822** [comment]
docker_start.sh脚本有问题，需要重新梳理一下
@vitahlin

**Comment by foww-0001** [comment]
换成新的docker_start.sh脚本可以使用GPU训练。
