### ISSUE TITLE
开发docker

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_docker#25]
供开发者使用的docker

**Comment by lpj0822** [comment]
cmake version >= 3.12

sudo apt install libasio-dev libtinyxml2-dev

sudo apt-get install libncurses5-dev

sudo apt-get install autoconf automake libtool

安装protobuffer:

https://github.com/protocolbuffers/protobuf/releases 下载 3.3.0版本
安装python3.5-dev:

sudo apt-get install python3.5-dev
安装googletest:

https://github.com/google/googletest 下载1.10.0版本
下载安装gflags,

https://github.com/gflags/gflags 下载2.2.0版本（安装动态库）
下载glog源码，编译安装：

https://github.com/google/glog.git 下载0.3.5版本（安装动态库）
下载poco源码，编译安装：

https://github.com/pocoproject/poco 下载1.8.0版本
下载Foonathan memory源码，编译安装：

https://github.com/eProsima/foonathan_memory_vendor
下载Fast-CDR源码，编译安装：

https://github.com/ApolloAuto/Fast-CDR 下载apollo分支代码
下载Fast-RTPS源码，编译安装：

https://github.com/ApolloAuto/Fast-RTPS 下载apollo分支代码
备注：编译可能遇到报错，std::function相关，打开对应文件#include

**Comment by vitahlin** [comment]
- [x] CMake
- [x] Protobuffer
- [x] googletest
- [ ] gflags
- [ ] glog
- [ ] poco
- [ ] Foonathan memory
- [ ] Fast-CDR
- [ ] Fast-RTPS
- [ ] OpenCV

**Comment by lpj0822** [comment]
先按cmake
https://blog.csdn.net/qq_38196982/article/details/102819749

**Comment by lpj0822** [comment]
在安装opencv
https://blog.csdn.net/weixin_41624766/article/details/90641375

**Comment by vitahlin** [comment]
https://yeasy.gitbook.io/docker_practice/install/mirror

**Comment by lpj0822** [comment]
opencv环境变量
```
printf '#OpenCV\nPKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig\nexport PKG_CONFIG_PATH\n' >> ~/.bashrc   
 
source ~/.bashrc 
```

**Comment by MiniBullLab** [comment]
CMake Warning at cmake/OpenCVDownload.cmake:193 (message):
  IPPICV: Download failed: 7;"Couldn't connect to server"

  For details please refer to the download log file:

  /opencv/opencv/build/CMakeDownloadLog.txt

Call Stack (most recent call first):
  3rdparty/ippicv/ippicv.cmake:42 (ocv_download)
  cmake/OpenCVFindIPP.cmake:243 (download_ippicv)
  cmake/OpenCVFindLibsPerf.cmake:12 (include)
  CMakeLists.txt:794 (include)

**Comment by vitahlin** [comment]
```
[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathMatrixAlgo.cpp.o
Traceback (most recent call last):
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 302, in build
  File "compose/project.py", line 468, in build
  File "compose/project.py", line 450, in build_service
  File "compose/service.py", line 1147, in build
compose.service.BuildError: (<Service: workspace>, {'stream': '[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathFun.cpp.o\n[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathVec.cpp.o\n[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathMatrixAlgo.cpp.o\n'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[7684] Failed to execute script docker-compose
make: *** [build] Error 255
```

**Comment by vitahlin** [comment]
```
[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathVec.cpp.o
[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathMatrixAlgo.cpp.o
Traceback (most recent call last):
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 302, in build
  File "compose/project.py", line 468, in build
  File "compose/project.py", line 450, in build_service
  File "compose/service.py", line 1147, in build
compose.service.BuildError: (<Service: workspace>, {'stream': '[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathFun.cpp.o\n[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathVec.cpp.o\n[ 10%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath/ImathMatrixAlgo.cpp.o\n'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 78, in main
TypeError: can only concatenate str (not "dict") to str
[7684] Failed to execute script docker-compose
make: *** [build] Error 255
```

**Comment by lpj0822** [comment]
qt5:
https://hub.docker.com/r/rabits/qt/dockerfile/

**Comment by lpj0822** [comment]
先安装gflags,然后安装glog，在安装opencv
@vitahlin

**Comment by MiniBullLab** [comment]
docker里面图形界面显示:
https://blog.csdn.net/a806689294/article/details/111462627

**Comment by MiniBullLab** [comment]
qt5 docker
https://qiita.com/MasaNa43/items/bb9754b31dfb8e3848e6

**Comment by lpj0822** [comment]
VTK与PCL安装

**Comment by vitahlin** [comment]
QT编译错误：
```
Note: Also available for Linux: linux-clang linux-icc

Note: Disabling X11 Accessibility Bridge: D-Bus or AT-SPI is missing.

Note: No wayland-egl support detected. Cross-toolkit compatibility disabled.

WARNING: gperf is required to build QtWebEngine.

WARNING: bison is required to build QtWebEngine.

WARNING: flex is required to build QtWebEngine.

ERROR: Feature 'egl' was enabled, but the pre-condition '(features.opengl || features.openvg) && (features.angle || libs.egl)' failed.

ERROR: Feature 'gstreamer_1_0' was enabled, but the pre-condition 'libs.gstreamer_1_0' failed.

Check config.log for details.
```

@lpj0822

**Comment by lpj0822** [comment]
安装apex，https://github.com/NVIDIA/apex
切换到git checkout f3a960f80244cf9e80558ab30f7f7e8cbf03c0a0分支编译

**Comment by vitahlin** [comment]
这个是啥原因 需要先安装其他的前置依赖包吗

**Comment by lpj0822** [comment]
什么问题？

**Comment by vitahlin** [comment]
ERROR: Feature 'egl' was enabled, but the pre-condition '(features.opengl || features.openvg) && (features.angle || libs.egl)' failed.

ERROR: Feature 'gstreamer_1_0' was enabled, but the pre-condition 'libs.gstreamer_1_0' failed.
就是这个，是需要安装前置依赖包吗

**Comment by lpj0822** [comment]
这个我没有遇到，要安装openGL？

**Comment by vitahlin** [comment]
https://stackoverflow.com/questions/49032560/no-wayland-egl-support-detected-cross-toolkit-compatibility-disabled

**Comment by vitahlin** [comment]
依赖库目前来看已经安装完，合并workspace分支代码
