### ISSUE TITLE
centos7 docker

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_docker#27]
https://blog.csdn.net/bewithme/article/details/105092159

**Comment by lpj0822** [comment]
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-docker-on-centos-8

**Comment by lpj0822** [comment]
https://docs.docker.com/engine/install/centos/#install-from-a-package

**Comment by lpj0822** [comment]
python3 install
```
sudo yum install python36
sudo yum install openssl-devel -y 
sudo yum install zlib-devel -y
```

**Comment by lpj0822** [comment]
centos7 安装docker已完成，参考scripts/install/centos_docker_install.sh

**Comment by lpj0822** [comment]
脚本需要测试

**Comment by lpj0822** [comment]
@foww-0001

**Comment by vitahlin** [comment]
测试结果提交另外的issue
