### ISSUE TITLE
workspace镜像分层后，最终镜像大小和原先一样大，解决该问题

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_docker#45]
- [ ] 1.镜像分层后，最后一层workspace镜像大小需控制在几百兆大小之内
- [x] 2.镜像分层考虑细化问题，即是否考虑多分几层
- [x] 3.使用公共的docker hub去编译镜像
- [x] 4.整理编译脚本与运行脚本

**Comment by vitahlin** [comment]
镜像分层不确定各层的大小相互独立，待确认，新建issue处理接镜像大小优化的问题

**Comment by vitahlin** [comment]
分层方案目前来看不可行
