### ISSUE TITLE
镜像的root权限处理

### ISSUE THREAD

**Issue by vitahlin** [MiniBullLab/easy_docker#5]
看下这个是不是想要的结果：
- https://blog.51cto.com/yangzhiming/2384688
- https://www.cnblogs.com/sparkdev/p/9614326.html
@lpj0822

**Comment by MiniBullLab** [comment]
这块主要是需要，在进入镜像后，用户无法修改系统文件，也就不能在镜像中安装自己的软件，只能修改挂载的这个目录

**Comment by MiniBullLab** [comment]
上传到百度网盘参考资料中的两个shell脚本

**Comment by vitahlin** [comment]
也不能在镜像中安装自己的软件，这个确定吗，在sh中暂时没看到相关配置
@lpj0822

**Comment by MiniBullLab** [comment]
如果脚本里面没有，就不需要
