### ISSUE TITLE
easy_docker文档完善

### ISSUE THREAD

**Issue by lpj0822** [MiniBullLab/easy_docker#75]

**Comment by kingwangxiang** [comment]
完善文档

**Comment by vitahlin** [comment]
邀请链接：邀你加入「EasyAI」知识库: https://www.yuque.com/g/vitah/eif9ua/collaborator/join?token=YNIsYAvcHMwSkJYQ# (成员)

**Comment by lpj0822** [comment]
文档如果编辑好，在readme里面放一个公共链接
